### ISSUE TITLE
Fixed bug in issue # 106 is still occurring

### ISSUE THREAD

**Issue by shshshshgoodnj** [mattwhitfield/Unitverse#224] opened 2023-05-25 05:56 UTC
https://github.com/mattwhitfield/Unitverse/pull/106 corrected the error for TC generation of internal classes, private classes.

However, whenever I generator TCs, I get error 'Cannot access protected property 'EquityContract' here'

If I set 'Emit tests for internal members: false',I get the same error.
How do I prevent TCs from being generated for internal classes?

**Comment by mattwhitfield** [comment] 2023-05-29 12:08
How is 'EmitSubclassForProtectedMethods' set?

Usually, for protected methods, it will derive a sub class that exposes protected things with public wrappers. It may be the case that 'EmitSubclassForProtectedMethods' is false, but it's still emitting tests for the protected property?

If you could put together a small repro it would be helpful 👍

**Comment by shshshshgoodnj** [comment] 2023-05-30 00:47
yes, I did not checked 'EmitSubclassForProtectedMethod'
but it is still emitting tests for members of protected class(internal class, private class)

I want to emit test for members of protected class



If you could put together a small repro it would be helpful 👍

> An example of an issue is the same as that link. 
https://github.com/mattwhitfield/Unitverse/issues/105

**Comment by mattwhitfield** [comment] 2023-05-30 09:55
Ok - as you can see from that PR, that example is in the unit tests now - and it doesn't repro - so there must be something different going on. 

Also there's no such thing as a protected class - so I'm trying to understand what the issue is - hence the request for a repro 👍

What version does Unitverse show in the help -> about dialog in Visual Studio?

**Comment by shshshshgoodnj** [comment] 2023-05-31 01:44
Checked Unitverse generation options:
```c#
Mocking framework type : Moq
Test framework type : MsTest
Emit subclass for protected member : False
Emit tests for internal members : False
``` 

Given:
```c#
using System;

namespace Prime.Services
{
    internal class PrimeService
    {
        public bool IsPrime(int candidate)
        {
            throw new NotImplementedException("Please create a test first.");
        }
    }
}
``` 
generate test:
```c#
namespace TestProject1
{
    using System;
    using AutoFixture;
    using AutoFixture.AutoMoq;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Prime.Services;

    [TestClass]
    public class PrimeServiceTests
    {
        private PrimeService _testClass;
        private IFixture _fixture;

        [TestInitialize]
        public void SetUp()
        {
            _fixture = new Fixture().Customize(new AutoMoqCustomization());
            _testClass = _fixture.Create<PrimeService>();
        }

        [TestMethod]
        public void CanCallIsPrime()
        {
            // Arrange
            var candidate = _fixture.Create<int>();

            // Act
            var result = _testClass.IsPrime(candidate);

            // Assert
            Assert.Fail("Create or modify test");
        }
    }
}
``` 


Gives me this error:
```c#
'Prime.Services' is inaccessible due to its protection level
``` 

What version does Unitverse show in the help

> The version of visual studio I'm using is the 2019 version and the version of Unitverse is Unitverse-0.193.0.(2019)

**Comment by mattwhitfield** [comment] 2023-05-31 16:02
Ok - so this is by design. You're asking it to generate for an internal class - so it's generating the tests. The usual thing that happens with internal classes is that you define an `InternalsVisibleTo` attribute on the source assembly, that gives the test assembly access to internal classes.

So my question would be - why are you generating tests for the internal class, if you don't want tests for internal classes? Is it the case that you are generating tests for multiple classes at a time, and you'd like it to skip generation for internal ones?

**Comment by shshshshgoodnj** [comment] 2023-06-01 00:22
I want to generate tests for multiple classes at a time, and I'd like to skip generation for internal classes.

**Comment by mattwhitfield** [comment] 2023-06-01 12:36
Ok - well, that's a very different request :) I'm going to close this one, and re-open it as a feature request.

**Closed by mattwhitfield** 2023-06-01 12:36 UTC
Labels: bug
